<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="teaser-content">
        <div class="row">
            <div class="col-xs-12">
                <?php if ($this->isDefault()) {  ?>
                    <p class="aam-info">
                        <?php echo AAM_Backend_View_Helper::preparePhrase('Define the [default] teaser message for all users, roles and visitors when access is limited to any post on your website.', 'strong'); ?>
                    </p>
                <?php } else { ?>
                    <p class="aam-info">
                        <?php echo sprintf(AAM_Backend_View_Helper::preparePhrase('Customize the teaser message for this %s when access is limited to any post, page or custom post type on your website.'), AAM_Backend_View::getSubject()->getUID()); ?>
                    </p>
                <?php } ?>
                <div class="aam-overwrite" id="aam-teaser-overwrite" style="display: <?php echo ($this->isOverwritten() ? 'block' : 'none'); ?>">
                    <span><i class="icon-check"></i> Settings are customized</span>
                    <span><a href="#" id="teaser-reset" class="btn btn-xs btn-primary">Reset To Default</a></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div>
                    <div class="form-group">
                        <label><?php echo __('Teaser Message', AAM_KEY); ?></label>
                        <textarea class="form-control" name="frontend.teaser.message" rows="3" placeholder="<?php echo __('Enter teaser message...', AAM_KEY); ?>"><?php echo stripslashes($this->getOption('frontend.teaser.message')); ?></textarea>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="frontend.teaser.excerpt"  value="1" <?php echo intval($this->getOption('frontend.teaser.excerpt')) ? 'checked' : ''; ?> />
                            <?php echo __('Add excerpt before teaser message', AAM_KEY); ?>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php }