<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="contact-content">
        <div class="row">
            <div class="col-xs-12">
                <p class="aam-info">
                    <?php echo __('Contact us if you have any questions or concerns but follow few simple rules:'); ?>
                </p>
                <ol class="text-larger">
                    <li>Keep your message short. As longer message as more times we will take to response;</li>
                    <li>Use English, Polish, Russian or Ukrainian language. Otherwise we may ignore your message;</li>
                    <li>In case of a problem with the plugin, include screenshots, videos or step-by-step description on how to reproduce the issue;</li>
                    <li>Email us at <a href="mailto:support@aamplugin.com" class="aam-highlight">support@aamplugin.com</a>, add us to Google Hangout or submit contact form on <a href="https://aamplugin.com/help" target="_blank">aamplugin.com</a> website to speed-up the response. Any other channels of communication we will be ignored.</li>
                    <li>Be patient. It might take up to 3 business days for us to response.</li>
                </ol>
            </div>
        </div>
    </div>
<?php }