<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="security-content">
        <table class="table table-striped table-bordered">
            <tbody>
                <?php do_action('aam-pre-security-content-action'); ?>
                
                <?php foreach($this->getOptionList() as $id => $option) { ?>
                    <tr>
                        <td>
                            <span class='aam-setting-title'><?php echo $option['title']; ?></span>
                            <p class="aam-setting-description">
                                <?php echo $option['descr']; ?>
                            </p>
                        </td>
                        <td class="text-center">
                            <input type="checkbox" name="<?php echo $id; ?>" id="security-<?php echo $id; ?>" <?php echo ($option['value'] ? 'checked' : ''); ?> /> <label for="security-<?php echo $id; ?>"></label>
                        </td>
                    </tr>
                <?php } ?>
                    
                <?php do_action('aam-post-security-content-action'); ?>
            </tbody>
        </table>
        
        <?php if (AAM_Backend_View_CodePinch::isInstalled() === false) { ?>
        <div class="metabox-holder">
            <div class="postbox">
                <div class="inside text-center">
                    <div class="inner-sm">
                        <p class="text-muted text-larger"><?php echo __('Improve your website security and keep your website error free with CodePinch.', AAM_KEY); ?></p>
                        <a href="<?php echo AAM_Backend_View_CodePinch::getUrl(AAM_CODEPINCH_AFFILIATE_CODE); ?>" class="btn btn-lg btn-success" target="_blank">
                            Install Free Plugin
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
<?php }